INSERT INTO CONTRIBUTOR (first_name, last_name, contributor_id, email, city) VALUES
  ('Pratap', 'Narayan', 'Abcs678xyq', 'abc@gmail.com', 'Bangalore'),
  ('Rajesh', 'Prasad', 'Abcs678xyX', 'xyz@email.com', 'Bangalore'),
  ('Sankalp', 'Nishad', 'Abcs678xYz', 'cap@marvel.com', 'Bangalore'),
  ('Pratap', 'Narayan', 'Abcs678xyA', 'abc@gmail.com', 'Bangalore'),
  ('Rajesh', 'Prasad', 'Abcs678xyB', 'xyz@email.com', 'Bangalore'),
  ('Sankalp', 'Nishad', 'Abcs678xyC', 'cap@marvel.com', 'Bangalore'),
  ('Pratap', 'Narayan', 'Abcs678xyD', 'abc@gmail.com', 'Bangalore'),
  ('Rajesh', 'Prasad', 'Abcs678xyE', 'xyz@email.com', 'Bangalore'),
  ('Sankalp', 'Nishad', 'Abcs678xyF', 'cap@marvel.com', 'Bangalore'),
  ('Pratap', 'Narayan', 'Abcs678xyG', 'abc@gmail.com', 'Bangalore'),
  ('Rajesh', 'Prasad', 'Abcs678xyH', 'xyz@email.com', 'Bangalore'),
  ('Sankalp', 'Nishad', 'Abcs678xyI','cap@marvel.com', 'Bangalore'),
  ('Pratap', 'Narayan', 'Abcs678xyJ','abc@gmail.com', 'Bangalore'),
  ('Rajesh', 'Prasad', 'Abcs678xyK','xyz@email.com', 'Bangalore'),
  ('Sankalp', 'Nishad', 'Abcs678xyL','cap@marvel.com', 'Bangalore'),
  ('Pratap', 'Narayan', 'Abcs678xyM','abc@gmail.com', 'Bangalore'),
  ('Rajesh', 'Prasad', 'Abcs678xyN','xyz@email.com', 'Bangalore'),
  ('Sankalp', 'Nishad', 'Abcs678xyO','cap@marvel.com', 'Bangalore'),
  ('Pratap', 'Narayan', 'Abcs678xyP','abc@gmail.com', 'Bangalore'),
  ('Rajesh', 'Prasad', 'Abcs678xyQ','xyz@email.com', 'Bangalore'),
  ('Sankalp', 'Nishad', 'Abcs678xyR','cap@marvel.com', 'Bangalore'),
  ('Pratap', 'Narayan', 'Abcs678xyS','abc@gmail.com', 'Bangalore'),
  ('Rajesh', 'Prasad', 'Abcs678xyT','xyz@email.com', 'Bangalore'),
  ('Sankalp', 'Nishad', 'Abcs678xyU','cap@marvel.com', 'Bangalore'),
  ('Pratap', 'Narayan', 'Abcs678xyV','abc@gmail.com', 'Bangalore'),
  ('Rajesh', 'Prasad', 'Abcs678xyW','xyz@email.com', 'Bangalore'),
  ('Sankalp', 'Nishad', 'Abcs678xy1','cap@marvel.com', 'Bangalore'),
  ('Pratap', 'Narayan', 'Abcs678xy2','abc@gmail.com', 'Bangalore'),
  ('Rajesh', 'Prasad', 'Abcs678xy3','xyz@email.com', 'Bangalore'),
  ('Sankalp', 'Nishad', 'Abcs678xy4','cap@marvel.com', 'Bangalore'),
  ('Pratap', 'Narayan', 'Abcs678xy5','abc@gmail.com', 'Bangalore'),
  ('Rajesh', 'Prasad', 'Abcs678xy6','xyz@email.com', 'Bangalore'),
  ('Sankalp', 'Nishad', 'Abcs678xy7','cap@marvel.com', 'Bangalore'),
  ('Pratap', 'Narayan', 'Abcs678xy8','abc@gmail.com', 'Bangalore'),
  ('Rajesh', 'Prasad', 'Abcs678xy9','xyz@email.com', 'Bangalore'),
  ('Sankalp', 'Nishad', 'Abcs678xy0','cap@marvel.com', 'Bangalore'),
  ('Pratap', 'Narayan', 'Abcs678xAq','abc@gmail.com', 'Bangalore'),
  ('Rajesh', 'Prasad', 'Abcs678xBq','xyz@email.com', 'Bangalore'),
  ('Sankalp', 'Nishad', 'Abcs678xCq','cap@marvel.com', 'Bangalore'),
  ('Pratap', 'Narayan', 'Abcs678xDq','abc@gmail.com', 'Bangalore'),
  ('Rajesh', 'Prasad', 'Abcs678xEq','xyz@email.com', 'Bangalore'),
  ('Sankalp', 'Nishad', 'Abcs678xFq','cap@marvel.com', 'Bangalore'),
  ('Pratap', 'Narayan', 'Abcs678xGq','abc@gmail.com', 'Bangalore'),
  ('Rajesh', 'Prasad', 'Abcs678xHq','xyz@email.com', 'Bangalore'),
  ('Sankalp', 'Nishad', 'Abcs678xyq','cap@marvel.com', 'Bangalore'),
  ('Pratap', 'Narayan', 'Abcs678xyq','abc@gmail.com', 'Bangalore'),
  ('Rajesh', 'Prasad', 'Abcs678xyq','xyz@email.com', 'Bangalore'),
  ('Sankalp', 'Nishad', 'Abcs678xyq','cap@marvel.com', 'Bangalore'),
  ('Pratap', 'Narayan', 'Abcs678xyq','abc@gmail.com', 'Bangalore'),
  ('Rajesh', 'Prasad', 'Abcs678xyq','xyz@email.com', 'Bangalore'),
  ('Sankalp', 'Nishad', 'Abcs678xyq','cap@marvel.com', 'Bangalore'),
  ('Pratap', 'Narayan', 'Abcs678xyq','abc@gmail.com', 'Bangalore'),
  ('Rajesh', 'Prasad', 'Abcs678xyq','xyz@email.com', 'Bangalore'),
  ('Sankalp', 'Nishad', 'Abcs678xyq','cap@marvel.com', 'Bangalore'),
  ('Pratap', 'Narayan', 'Abcs678xyq','abc@gmail.com', 'Bangalore'),
  ('Rajesh', 'Prasad', 'Abcs678xyq','xyz@email.com', 'Bangalore'),
  ('Sankalp', 'Nishad', 'Abcs678xyq','cap@marvel.com', 'Bangalore'),
  ('Pratap', 'Narayan', 'Abcs678xyq','abc@gmail.com', 'Bangalore'),
  ('Rajesh', 'Prasad', 'Abcs678xyq','xyz@email.com', 'Bangalore'),
  ('Sankalp', 'Nishad', 'Abcs678xyq','cap@marvel.com', 'Bangalore'),
  ('Pratap', 'Narayan', 'Abcs678xyq','abc@gmail.com', 'Bangalore'),
  ('Rajesh', 'Prasad', 'Abcs678xyq','xyz@email.com', 'Bangalore'),
  ('Sankalp', 'Nishad', 'Abcs678xyq','cap@marvel.com', 'Bangalore'),
  ('Pratap', 'Narayan', 'Abcs678xyq','abc@gmail.com', 'Noida'),
  ('Rajesh', 'Prasad', 'Abcs678xyq','xyz@email.com', 'Noida'),
  ('Sankalp', 'Nishad', 'Abcs678xyq','cap@marvel.com', 'Noida'),
  ('Pratap', 'Narayan', 'Abcs678xyq','abc@gmail.com', 'Noida'),
  ('Rajesh', 'Prasad', 'Abcs678xyq','xyz@email.com', 'Noida'),
  ('Sankalp', 'Nishad', 'Abcs678xyq','cap@marvel.com', 'Noida'),
  ('Pratap', 'Narayan', 'Abcs678xyq','abc@gmail.com', 'Noida'),
  ('Rajesh', 'Prasad', 'Abcs678xyq','xyz@email.com', 'Noida'),
  ('Sankalp', 'Nishad', 'Abcs678xyq','cap@marvel.com', 'Noida'),
  ('Pratap', 'Narayan', 'Abcs678xyq','abc@gmail.com', 'Noida'),
  ('Rajesh', 'Prasad', 'Abcs678xyq','xyz@email.com', 'Noida'),
  ('Sankalp', 'Nishad', 'Abcs678xyq','cap@marvel.com', 'Noida'),
  ('Pratap', 'Narayan', 'Abcs678xyq','abc@gmail.com', 'Noida'),
  ('Rajesh', 'Prasad', 'Abcs678xyq','xyz@email.com', 'Noida'),
  ('Sankalp', 'Nishad', 'Abcs678xyq','cap@marvel.com', 'New York'),
  ('Pratap', 'Narayan', 'Abcs678xyq','abc@gmail.com', 'New York'),
  ('Rajesh', 'Prasad', 'Abcs678xyq','xyz@email.com', 'New York'),
  ('Sankalp', 'Nishad', 'Abcs678xyq', 'cap@marvel.com', 'New York'),
  ('Pratap', 'Narayan', 'Abcs678xyq', 'abc@gmail.com', 'New York'),
  ('Rajesh', 'Prasad', 'Abcs678xyq', 'xyz@email.com', 'New York'),
  ('Sankalp', 'Nishad', 'Abcs678xyq', 'cap@marvel.com', 'New York'),
  ('Pratap', 'Narayan', 'Abcs678xyq', 'abc@gmail.com', 'New York'),
  ('Rajesh', 'Prasad', 'Abcs678xyq', 'xyz@email.com', 'New York'),
  ('Sankalp', 'Nishad', 'Abcs678xyq', 'cap@marvel.com', 'New York'),
  ('Pratap', 'Narayan', 'Abcs678xyq', 'abc@gmail.com', 'New York'),
  ('Rajesh', 'Prasad', 'Abcs678xyq', 'xyz@email.com', 'New York'),
  ('Sankalp', 'Nishad', 'Abcs678xyq', 'cap@marvel.com', 'New York'),
  ('Pratap', 'Narayan', 'Abcs678xyq', 'abc@gmail.com', 'Bangalore'),
  ('Rajesh', 'Prasad', 'Abcs678xyq', 'xyz@email.com', 'Bangalore'),
  ('Sankalp', 'Nishad', 'Abcs678xyq', 'cap@marvel.com', 'Bangalore'),
  ('Pratap', 'Narayan', 'Abcs678xyq', 'abc@gmail.com', 'Bangalore'),
  ('Rajesh', 'Prasad', 'Abcs678xyq', 'xyz@email.com', 'Bangalore'),
  ('Sankalp', 'Nishad', 'Abcs678xyq', 'cap@marvel.com', 'Bangalore'),
  ('Pratap', 'Narayan', 'Abcs678xyq', 'abc@gmail.com', 'Bangalore'),
  ('Rajesh', 'Prasad', 'Abcs678xyq', 'xyz@email.com', 'Bangalore'),
  ('Sankalp', 'Nishad', 'Abcs678xyq', 'cap@marvel.com', 'Bangalore'),
  ('Pratap', 'Narayan', 'Abcs678xyq', 'abc@gmail.com', 'Bangalore'),
  ('Rajesh', 'Prasad', 'Abcs678xyq', 'xyz@email.com', 'Bangalore'),
  ('Sankalp', 'Nishad', 'Abcs678xyq', 'cap@marvel.com', 'Bangalore'),
  ('Pratap', 'Narayan', 'Abcs678xyq', 'abc@gmail.com', 'Bangalore'),
  ('Rajesh', 'Prasad', 'Abcs678xyq', 'xyz@email.com', 'Bangalore'),
  ('Sankalp', 'Nishad', 'Abcs678xyq', 'cap@marvel.com', 'Bangalore'),
  ('Pratap', 'Narayan', 'Abcs678xyq', 'abc@gmail.com', 'Bangalore'),
  ('Rajesh', 'Prasad', 'Abcs678xyq', 'xyz@email.com', 'Bangalore'),
  ('Sankalp', 'Nishad', 'Abcs678xyq', 'cap@marvel.com', 'Bangalore'),
  ('Pratap', 'Narayan', 'Abcs678xyq', 'abc@gmail.com', 'Bangalore'),
  ('Rajesh', 'Prasad', 'Abcs678xyq', 'xyz@email.com', 'Bangalore'),
  ('Sankalp', 'Nishad', 'Abcs678xyq', 'cap@marvel.com', 'Bangalore'),
  ('Pratap', 'Narayan', 'Abcs678xyq', 'abc@gmail.com', 'Bangalore'),
  ('Rajesh', 'Prasad', 'Abcs678xyq', 'xyz@email.com', 'Bangalore'),
  ('Sankalp', 'Nishad', 'Abcs678xyq', 'cap@marvel.com', 'Bangalore'),
  ('Pratap', 'Narayan', 'Abcs678xyq', 'abc@gmail.com', 'Bangalore'),
  ('Rajesh', 'Prasad', 'Abcs678xyq', 'xyz@email.com', 'Bangalore'),
  ('Sankalp', 'Nishad', 'Abcs678xyq', 'cap@marvel.com', 'Bangalore'),
  ('Pratap', 'Narayan', 'Abcs678xyq', 'abc@gmail.com', 'Bangalore'),
  ('Rajesh', 'Prasad', 'Abcs678xyq', 'xyz@email.com', 'Bangalore'),
  ('Sankalp', 'Nishad', 'Abcs678xyq', 'cap@marvel.com', 'Bangalore'),
  ('Pratap', 'Narayan', 'Abcs678xyq', 'abc@gmail.com', 'Bangalore'),
  ('Rajesh', 'Prasad', 'Abcs678xyq', 'xyz@email.com', 'Bangalore'),
  ('Sankalp', 'Nishad', 'Abcs678xyq', 'cap@marvel.com', 'Bangalore'),
  ('Pratap', 'Narayan', 'Abcs678xyq', 'abc@gmail.com', 'Bangalore'),
  ('Rajesh', 'Prasad', 'Abcs678xyq', 'xyz@email.com', 'Bangalore'),
  ('Sankalp', 'Nishad', 'Abcs678xyq', 'cap@marvel.com', 'Bangalore'),
  ('Pratap', 'Narayan', 'Abcs678xyq', 'abc@gmail.com', 'Bangalore'),
  ('Rajesh', 'Prasad', 'Abcs678xyq', 'xyz@email.com', 'Bangalore'),
  ('Sankalp', 'Nishad', 'Abcs678xyq', 'cap@marvel.com', 'Bangalore'),
  ('Pratap', 'Narayan', 'Abcs678xyq', 'abc@gmail.com', 'Bangalore'),
  ('Rajesh', 'Prasad', 'Abcs678xyq', 'xyz@email.com', 'Bangalore'),
  ('Sankalp', 'Nishad', 'Abcs678xyq', 'cap@marvel.com', 'Bangalore'),
  ('Pratap', 'Narayan', 'Abcs678xyq', 'abc@gmail.com', 'Bangalore'),
  ('Rajesh', 'Prasad', 'Abcs678xyq', 'xyz@email.com', 'Bangalore'),
  ('Sankalp', 'Nishad', 'Abcs678xyq', 'cap@marvel.com', 'Bangalore'),
  ('Pratap', 'Narayan', 'Abcs678xyq', 'abc@gmail.com', 'Bangalore'),
  ('Rajesh', 'Prasad', 'Abcs678xyq', 'xyz@email.com', 'Bangalore'),
  ('Sankalp', 'Nishad', 'Abcs678xyq', 'cap@marvel.com', 'Bangalore'),
  ('Pratap', 'Narayan', 'Abcs678xyq', 'abc@gmail.com', 'Bangalore'),
  ('Rajesh', 'Prasad', 'Abcs678xyq', 'xyz@email.com', 'Bangalore'),
  ('Sankalp', 'Nishad', 'Abcs678xyq', 'cap@marvel.com', 'Bangalore'),
  ('Pratap', 'Narayan', 'Abcs678xyq', 'abc@gmail.com', 'Bangalore'),
  ('Rajesh', 'Prasad', 'Abcs678xyq', 'xyz@email.com', 'Bangalore'),
  ('Sankalp', 'Nishad', 'Abcs678xyq', 'cap@marvel.com', 'Bangalore'),
  ('Pratap', 'Narayan', 'Abcs678xyq', 'abc@gmail.com', 'Bangalore'),
  ('Rajesh', 'Prasad', 'Abcs678xyq', 'xyz@email.com', 'Bangalore'),
  ('Sankalp', 'Nishad', 'Abcs678xyq', 'cap@marvel.com', 'Bangalore'),
  ('Pratap', 'Narayan', 'Abcs678xyq', 'abc@gmail.com', 'Bangalore'),
  ('Rajesh', 'Prasad', 'Abcs678xyq', 'xyz@email.com', 'Bangalore'),
  ('Sankalp', 'Nishad', 'Abcs678xyq', 'cap@marvel.com', 'Gurugram'),
  ('Pratap', 'Narayan', 'Abcs678xyq', 'abc@gmail.com', 'Gurugram'),
  ('Rajesh', 'Prasad', 'Abcs678xyq', 'xyz@email.com', 'Gurugram'),
  ('Sankalp', 'Nishad', 'Abcs678xyq', 'cap@marvel.com', 'Gurugram'),
  ('Pratap', 'Narayan', 'Abcs678xyq', 'abc@gmail.com', 'Gurugram'),
  ('Rajesh', 'Prasad', 'Abcs678xyq', 'xyz@email.com', 'Gurugram'),
  ('Sankalp', 'Nishad', 'Abcs678xyq', 'cap@marvel.com', 'Gurugram'),
  ('Pratap', 'Narayan', 'Abcs678xyq', 'abc@gmail.com', 'Gurugram'),
  ('Rajesh', 'Prasad', 'Abcs678xyq', 'xyz@email.com', 'Gurugram'),
  ('Sankalp', 'Nishad', 'Abcs678xyq', 'cap@marvel.com', 'Gurugram')
  ;