CREATE TABLE CONTRIBUTOR (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  contributor_id VARCHAR(50) NOT NULL,
  first_name VARCHAR(50) NOT NULL,
  last_name VARCHAR(50) NOT NULL,
  email VARCHAR(100) DEFAULT NULL,
  city VARCHAR(100) NOT NULL
);